server:
  port: 8080 #example

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/fitness" #example
    username: "postgres" #example
    password: "postgres" #example
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: "app"

  mail:
    username: "mymail@mail.ru" #example
    password: "mysecretpassword" #example
    host: "smtp.mail.ru"
    port: 465
    protocol: "smtp"
    default-encoding: "UTF-8"
    properties:
      mail:
        host: "smtp.mail.ru"
        from: "mymail@mail.ru" #example
        debug: true
        smtp:
          auth: true
          port: 465
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: "javax.net.ssl.SSLSocketFactory"
            fallback: false

excel:
  exampleFileName: "templates/excelExample.xlsx"
  sheetName: "Sheet0"

jwt:
  secret: "YourSecret" #example
  issuer: "YourName" #example

google:
  drive:
    port: 8888
    host: "localhost"
    folderId: "YourFolderId" #example
    queryForFileFolder: "'YourFolderId' in parents" #example
    userId: "user" #example
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    fileExtension: ".xlsx"
    applicationName: "Fitness studio"
    tokensDirectoryPath: "tokens"
    credentialsFilePath: "/credentials.json"
    accessType: "offline"
    fileAttachment: "attachment; filename="

email:
  textType: "text/html; charset=utf-8"
  verificationFileName: "verification-mail.ftl"
  registrationFileName: "registration-mail.ftl"
  userNameParamName: "name"
  mailAdressParamName: "mail"
  verificationCodeParamName: "code"
  maxSend: 3