server:
  port: 8080 #example

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/fitness" #example
    username: "postgres" #example
    password: "postgres" #example
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: "app"

mail:
  username: "mymail@mail.ru" #example
  password: "mysecretpassword" #example
  host: "smtp.mail.ru"
  port: 465
  protocol: "smtp"
  default-encoding: "UTF-8"
  properties:
    mail:
      host: "smtp.mail.ru"
      from: "mymail@mail.ru" #example
      debug: true
      smtp:
        auth: true
        port: 465
        starttls:
          enable: true
          required: true
        socketFactory:
          port: 465
          class: "javax.net.ssl.SSLSocketFactory"
          fallback: false

excel:
  columnUuid: "uuid"
  columnDtCreate: "dt_create"
  columnDtUpdate: "dt_update"
  columnMail: "user_mail"
  columnFio: "user_fio"
  columnRole: "user_role"
  columnText: "text"
  columnType: "type"
  columnId: "id"

jwt:
  secret: "YourSecret" #example
  issuer: "YourName" #example

google:
  drive:
    port: "80"
    host: "127.0.0.1"
    folderId: "YourFolderId" #example
    userId: "user" #example
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    fileExtension: ".xlsx"
    applicationName: "Fitness studio"
    tokensDirectoryPath: "tokens"
    credentialsFilePath: "/credentials.json"
    accessType: "offline"
    fileAttachment: "attachment; filename="