version: '3.5'
services:
  db:
    build: postgresql
    image: fitness_postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB: fitness
    networks:
      - fitness_ntwrk
  pgadmin:
    build: pgadmin
    image: fitness_pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
    ports:
      - "82:80"
    networks:
      - fitness_ntwrk
  swagger-ui:
    build: swagger-ui
    image: fitness_swagger-ui:1.0.0
    ports:
      - "81:8080"
    networks:
      - fitness_ntwrk
  FitnesStudioModul:
    build: FitnesStudioModul
    image: fitness_studio:1.0.0
    networks:
      - fitness_ntwrk
  proxy:
    build: proxy
    image: fitness_proxy:1.0.0
    ports:
      - "80:80"
    networks:
      - fitness_ntwrk
  ftp:
    build: ftp
    image: ftp:1.0.0
    environment:
      - FTP_USER=
      - FTP_PASS=
      - PASV_ADDRESS_RESOLVE=YES
      - PASV_ADDR_RESOLVE=YES
      - PASV_MIN_PORT=21100
      - PASV_MAX_PORT=21110
      - PASV_ADDRESS_ENABLE=YES
      - PASV_ENABLE=YES
      - LOG_STDOUT=1
    volumes:
      - ./support/vsftpd:/home/vsftpd
    ports:
      - "20:20"
      - "21:21"
      - "21100:21100"
      - "21101:21101"
      - "21102:21102"
      - "21103:21103"
      - "21104:21104"
      - "21105:21105"
      - "21106:21106"
      - "21107:21107"
      - "21108:21108"
      - "21109:21109"
      - "21110:21110"
    networks:
      - fitness_ntwrk
networks:
  fitness_ntwrk:
    name: fitness_ntwrk