server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ""
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
  open-in-view: false
mail:
  username: ""
  password: ""
  host: "smtp.mail.ru"
  port: 465
  protocol: "smtp"
  default-encoding: "UTF-8"
  properties:
    mail:
      host: "smtp.mail.ru"
      from: ""
      debug: true
      smtp:
        auth: true
        port: 465
        starttls:
          enable: true
          required: true
        socketFactory:
          port: 465
          class: "javax.net.ssl.SSLSocketFactory"
          fallback: false